services:
    datatables.container:
        class:  Nhacsam\DataTablesBundle\Services\DataTablesContainer
        arguments: [@doctrine, @router]

    
    
    
    
    datatable.twig:
        class:        Nhacsam\DataTablesBundle\Twig\Extension\DataTablesExtension
        arguments:   [@datatables.container]
        tags:
            - { name: twig.extension }