parameters:
    nhacsam_datatables.config: ~

services:
    datatables.container:
        class:  Nhacsam\DataTablesBundle\Services\DataTablesContainer
        arguments: [%nhacsam_datatables.config%, @doctrine, @router]

    
    
    
    
    datatable.twig:
        class:        Nhacsam\DataTablesBundle\Twig\Extension\DataTablesExtension
        arguments:   [%nhacsam_datatables.config%, @datatables.container]
        tags:
            - { name: twig.extension }
